### ISSUE TITLE
執行時發生  NotImplementedError: Only the following pseudo-classes are implemented: nth-of-type.  錯誤

### ISSUE THREAD

**Issue by chenliTW** [nevikw39/ZeroJudge_Exporter#1]
環境：python3.6 (anaconda3)
OS：mac(已自行安裝chorme driver)

執行時發生錯誤，traceback如下
```
Traceback (most recent call last):
  File "ZeroJudge_Exporter.py", line 110, in <module>
    if '沒有發現任何資料!!' in soup.select_one('body > div.container > div > table > tr:nth-child(2) > td').text:
  File "/Users/chen/anaconda3/lib/python3.6/site-packages/bs4/element.py", line 1403, in select_one
    value = self.select(selector, limit=1)
  File "/Users/chen/anaconda3/lib/python3.6/site-packages/bs4/element.py", line 1609, in select
    for candidate in _use_candidate_generator(tag):
  File "/Users/chen/anaconda3/lib/python3.6/site-packages/bs4/element.py", line 1570, in recursive_select
    for i in tag.select(next_token, recursive_candidate_generator):
  File "/Users/chen/anaconda3/lib/python3.6/site-packages/bs4/element.py", line 1528, in select
    'Only the following pseudo-classes are implemented: nth-of-type.')
NotImplementedError: Only the following pseudo-classes are implemented: nth-of-type.
```

**Comment by nevikw39** [comment]
您好：
很抱歉這麼晚才回你
這裡看起來是 bs4 沒有實作 nth-child 這個關於表格的假類別。
可以把 109 行改成 `if '沒有發現任何資料!!' in soup.select_one('body > div.container > div > table').text:`，如果在英文環境要用 `'No Data!!'`。
感謝

**Comment by chenliTW** [comment]
謝謝，依照上述把 109 行改成``` if '沒有發現任何資料!!' in soup.select_one('body > div.container > div > table').text: ```問題就解決了！：）
